export const menu = [
  {
    id: 0,
    name: "Tartelletta al limone",
    quantity: 10,
    price: 7.0,
    ordered: 0,
    image: "/images/tartelletta.jpg",
  },
  {
    id: 1,
    name: "Gelato al cioccolato fondente",
    quantity: 10,
    price: 8.0,
    ordered: 0,
    image: "/images/gelato.jpg",
  },
  {
    id: 2,
    name: "Biscotto crema e frutta",
    quantity: 10,
    price: 7.5,
    ordered: 0,
    image: "/images/biscotto.jpg",
  },
  {
    id: 3,
    name: "Cheescake ai frutti di bosco",
    quantity: 10,
    price: 9.5,
    ordered: 0,
    image: "/images/cheescake.jpg",
  },
  {
    id: 4,
    name: "Mimosa",
    quantity: 10,
    price: 9.0,
    ordered: 0,
    image: "/images/mimosa.jpg",
  },
  {
    id: 5,
    name: "Tiramisu",
    quantity: 10,
    price: 8.0,
    ordered: 0,
    image: "/images/tiramisu.jpg",
  },
  {
    id: 6,
    name: "Regina",
    quantity: 10,
    price: 10.0,
    ordered: 0,
    image: "/images/regina.jpg",
  },
  {
    id: 7,
    name: "Macarons",
    quantity: 30,
    price: 2,
    ordered: 0,
    image: "/images/macarons.jpg",
  },
];
